version: '3.4'

services:
  webshop.api:
    image: ${DOCKER_REGISTRY-}webshopapi
    ports:
      - "8080:8080"
    networks:
      - ww
    build:
      context: .
      dockerfile: WebShop.Api/Dockerfile

  webshop.migrationrunner:
    image: ${DOCKER_REGISTRY-}webshopmigrationrunner
    networks:
      - ww
    build:
      context: .
      target: final
      dockerfile: WebShop.MigrationRunner/Dockerfile
    depends_on:
      - webshop.postgresdb

  webshop.postgresdb:
    networks:
      - ww
    image: "postgres"
    container_name: webshop.postgresdb

  pgAdmin:
    networks:
      - ww
    image: "dpage/pgadmin4"
    container_name: pgAdmin

networks:
  ww:
volumes:
  local_pgdata:
  pgadmin-data: